import type { DeckDefinition } from "./types";

export const SAMPLE_CARD_LIBRARY: DeckDefinition[] = [
  {
    id: "beech",
    kind: "tree",
    title: "山毛榉",
    species: "山毛榉",
    cost: 2,
    basePoints: 4,
    copies: 5,
    scoreRules: [{ type: "per-tree", species: "山毛榉", points: 1, label: "同种树木" }],
  },
  {
    id: "oak",
    kind: "tree",
    title: "橡树",
    species: "橡树",
    cost: 2,
    basePoints: 3,
    copies: 5,
    scoreRules: [{ type: "per-side", points: 1, label: "树上住民" }],
  },
  {
    id: "maple",
    kind: "tree",
    title: "大枫树",
    species: "大枫树",
    cost: 2,
    basePoints: 2,
    copies: 5,
    onPlay: [{ type: "draw-deck", count: 1, label: "林冠补牌" }],
    scoreRules: [{ type: "per-distinct-tree-species", points: 1, label: "树种多样性" }],
  },
  {
    id: "fir",
    kind: "tree",
    title: "冷杉",
    species: "冷杉",
    cost: 2,
    basePoints: 3,
    copies: 5,
    scoreRules: [{ type: "per-tag", tag: "鸟类", points: 1, label: "鸟类栖息" }],
  },
  {
    id: "birch",
    kind: "tree",
    title: "桦树",
    species: "桦树",
    cost: 2,
    basePoints: 2,
    copies: 5,
    onPlay: [{ type: "tuck-clearing", count: 1, label: "落叶覆盖" }],
    scoreRules: [{ type: "per-tag", tag: "昆虫", points: 1, label: "昆虫群落" }],
  },
  {
    id: "linden",
    kind: "tree",
    title: "椴树",
    species: "椴树",
    cost: 2,
    basePoints: 3,
    copies: 4,
    scoreRules: [{ type: "per-tag", tag: "蝙蝠", points: 1, label: "夜栖树冠" }],
  },
  {
    id: "horse-chestnut",
    kind: "tree",
    title: "欧洲七叶树",
    species: "欧洲七叶树",
    cost: 2,
    basePoints: 4,
    copies: 4,
    scoreRules: [{ type: "per-tag", tag: "蝴蝶", points: 1, label: "花序访客" }],
  },
  {
    id: "ash",
    kind: "tree",
    title: "梣树",
    species: "梣树",
    cost: 2,
    basePoints: 2,
    copies: 4,
    onPlay: [{ type: "tuck-clearing", count: 1, label: "树荫藏牌" }],
    scoreRules: [{ type: "per-tag", tag: "有爪动物", points: 1, label: "枝干落脚" }],
  },
  {
    id: "douglas-fir",
    kind: "tree",
    title: "花旗松",
    species: "花旗松",
    cost: 2,
    basePoints: 4,
    copies: 4,
    scoreRules: [{ type: "per-tag", tag: "鸟类", points: 1, label: "高枝鸟巢" }],
  },
  {
    id: "silver-fir",
    kind: "tree",
    title: "银杉",
    species: "银杉",
    cost: 2,
    basePoints: 3,
    copies: 4,
    onPlay: [{ type: "draw-deck", count: 1, label: "针叶补给" }],
    scoreRules: [{ type: "per-tag", tag: "植物", points: 1, label: "林下植被" }],
  },
  {
    id: "deer-boar",
    kind: "dweller",
    title: "林鹿 / 野猪",
    copies: 4,
    faces: [
      {
        id: "deer",
        title: "林鹿",
        side: "left",
        cost: 3,
        tags: ["鹿类", "偶蹄动物", "哺乳", "食草"],
        basePoints: 5,
        scoreRules: [{ type: "per-tree", points: 1, label: "开阔林地" }],
      },
      {
        id: "boar",
        title: "野猪",
        side: "right",
        cost: 2,
        tags: ["猪类", "偶蹄动物", "哺乳"],
        basePoints: 3,
        scoreRules: [{ type: "per-tag", tag: "蘑菇", points: 1, label: "翻找菌类" }],
      },
    ],
  },
  {
    id: "fox-rabbit",
    kind: "dweller",
    title: "狐狸 / 野兔",
    copies: 4,
    faces: [
      {
        id: "fox",
        title: "狐狸",
        side: "right",
        cost: 3,
        tags: ["哺乳", "捕食", "有爪动物"],
        basePoints: 4,
        scoreRules: [{ type: "per-tag", tag: "食草", points: 2, label: "猎物链" }],
      },
      {
        id: "rabbit",
        title: "野兔",
        side: "left",
        cost: 1,
        tags: ["兔类", "哺乳", "食草"],
        basePoints: 1,
        scoreRules: [{ type: "per-tag", tag: "植物", points: 1, label: "草本环境" }],
      },
    ],
  },
  {
    id: "owl-woodpecker",
    kind: "dweller",
    title: "猫头鹰 / 啄木鸟",
    copies: 4,
    faces: [
      {
        id: "owl",
        title: "猫头鹰",
        side: "top",
        cost: 2,
        tags: ["鸟类", "捕食", "有爪动物"],
        basePoints: 3,
        scoreRules: [{ type: "per-pair", tag: "哺乳", points: 2, label: "夜间猎场" }],
      },
      {
        id: "woodpecker",
        title: "啄木鸟",
        side: "top",
        cost: 1,
        tags: ["鸟类"],
        basePoints: 1,
        onPlay: [{ type: "draw-deck", count: 1, label: "啄洞觅食" }],
        scoreRules: [{ type: "per-tree", species: "冷杉", points: 2, label: "针叶树" }],
      },
    ],
  },
  {
    id: "butterfly-beetle",
    kind: "dweller",
    title: "蝴蝶 / 甲虫",
    copies: 5,
    faces: [
      {
        id: "butterfly",
        title: "蝴蝶",
        side: "top",
        cost: 1,
        tags: ["蝴蝶", "昆虫"],
        basePoints: 1,
        scoreRules: [{ type: "per-tag", tag: "植物", points: 1, label: "授粉" }],
      },
      {
        id: "beetle",
        title: "甲虫",
        side: "bottom",
        cost: 1,
        tags: ["昆虫"],
        basePoints: 2,
        scoreRules: [{ type: "per-tree", species: "桦树", points: 1, label: "树皮缝隙" }],
      },
    ],
  },
  {
    id: "fern-moss",
    kind: "dweller",
    title: "蕨类 / 苔藓",
    copies: 5,
    faces: [
      {
        id: "fern",
        title: "蕨类",
        side: "bottom",
        cost: 1,
        tags: ["植物"],
        basePoints: 1,
        scoreRules: [{ type: "per-side", points: 1, label: "树荫覆盖" }],
      },
      {
        id: "moss",
        title: "苔藓",
        side: "bottom",
        cost: 0,
        tags: ["植物"],
        basePoints: 0,
        onPlay: [{ type: "draw-deck", count: 1, label: "保水层" }],
        scoreRules: [{ type: "per-cave", points: 1, label: "腐殖质" }],
      },
    ],
  },
  {
    id: "mushroom-toad",
    kind: "dweller",
    title: "蘑菇 / 林蛙",
    copies: 4,
    faces: [
      {
        id: "mushroom",
        title: "蘑菇",
        side: "bottom",
        cost: 1,
        tags: ["蘑菇"],
        basePoints: 2,
        scoreRules: [{ type: "per-tag", tag: "蘑菇", points: 1, label: "菌丝网络" }],
      },
      {
        id: "toad",
        title: "林蛙",
        side: "left",
        cost: 2,
        tags: ["两栖"],
        basePoints: 3,
        scoreRules: [{ type: "per-tag", tag: "昆虫", points: 1, label: "捕虫" }],
      },
    ],
  },
  {
    id: "bat-moth",
    kind: "dweller",
    title: "蝙蝠 / 飞蛾",
    copies: 4,
    faces: [
      {
        id: "bat",
        title: "蝙蝠",
        side: "top",
        cost: 2,
        tags: ["蝙蝠", "哺乳", "夜行"],
        basePoints: 3,
        onPlay: [{ type: "tuck-clearing", count: 1, label: "藏入洞穴" }],
        scoreRules: [{ type: "per-cave", points: 1, label: "洞穴回声" }],
      },
      {
        id: "moth",
        title: "飞蛾",
        side: "top",
        cost: 0,
        tags: ["蛾类", "昆虫", "夜行"],
        basePoints: 0,
        scoreRules: [{ type: "per-tag", tag: "夜行", points: 1, label: "夜间活动" }],
      },
    ],
  },
  {
    id: "squirrel-jay",
    kind: "dweller",
    title: "松鼠 / 松鸦",
    copies: 4,
    faces: [
      {
        id: "squirrel",
        title: "松鼠",
        side: "right",
        cost: 1,
        tags: ["啮齿动物", "哺乳", "有爪动物"],
        basePoints: 2,
        scoreRules: [{ type: "per-tree", species: "橡树", points: 2, label: "橡果储藏" }],
      },
      {
        id: "jay",
        title: "松鸦",
        side: "top",
        cost: 1,
        tags: ["鸟类"],
        basePoints: 2,
        scoreRules: [{ type: "per-tree", species: "山毛榉", points: 1, label: "坚果传播" }],
      },
    ],
  },
  {
    id: "ivy-lichen",
    kind: "dweller",
    title: "常春藤 / 地衣",
    copies: 4,
    faces: [
      {
        id: "ivy",
        title: "常春藤",
        side: "left",
        cost: 1,
        tags: ["植物"],
        basePoints: 1,
        scoreRules: [{ type: "per-tree", points: 1, label: "攀援树干" }],
      },
      {
        id: "lichen",
        title: "地衣",
        side: "bottom",
        cost: 0,
        tags: ["植物", "蘑菇"],
        basePoints: 0,
        scoreRules: [{ type: "per-distinct-tree-species", points: 1, label: "空气指示" }],
      },
    ],
  },
  {
    id: "tawny-owl-stag-beetle",
    kind: "dweller",
    title: "灰林鸮 / 锹形虫",
    copies: 4,
    faces: [
      {
        id: "tawny-owl",
        title: "灰林鸮",
        side: "top",
        cost: 2,
        tags: ["鸟类", "捕食", "有爪动物"],
        basePoints: 3,
        scoreRules: [{ type: "per-pair", tag: "哺乳", points: 2, label: "夜间猎场" }],
      },
      {
        id: "stag-beetle",
        title: "锹形虫",
        side: "bottom",
        cost: 1,
        tags: ["昆虫", "有爪动物"],
        basePoints: 2,
        scoreRules: [{ type: "per-tree", species: "橡树", points: 1, label: "栎木腐殖" }],
      },
    ],
  },
  {
    id: "goshawk-fly-agaric",
    kind: "dweller",
    title: "苍鹰 / 毒蝇伞",
    copies: 4,
    faces: [
      {
        id: "goshawk",
        title: "苍鹰",
        side: "top",
        cost: 3,
        tags: ["鸟类", "捕食", "有爪动物"],
        basePoints: 4,
        scoreRules: [{ type: "per-tag", tag: "鸟类", points: 1, label: "猛禽领地" }],
      },
      {
        id: "fly-agaric",
        title: "毒蝇伞",
        side: "bottom",
        cost: 1,
        tags: ["蘑菇"],
        basePoints: 0,
        onPlay: [{ type: "tuck-clearing", count: 1, label: "菌环覆盖" }],
        scoreRules: [{ type: "per-tag", tag: "蘑菇", points: 1, label: "菌环扩张" }],
      },
    ],
  },
  {
    id: "long-eared-bat-hare",
    kind: "dweller",
    title: "普通长耳蝠 / 欧洲野兔",
    copies: 4,
    faces: [
      {
        id: "long-eared-bat",
        title: "普通长耳蝠",
        side: "top",
        cost: 1,
        tags: ["蝙蝠", "哺乳", "夜行"],
        basePoints: 2,
        scoreRules: [{ type: "per-cave", points: 1, label: "回声洞穴" }],
      },
      {
        id: "european-hare",
        title: "欧洲野兔",
        side: "left",
        cost: 1,
        tags: ["兔类", "哺乳", "食草"],
        basePoints: 1,
        scoreRules: [{ type: "per-position", side: "left", points: 1, label: "林缘活动" }],
      },
    ],
  },
  {
    id: "bat-duo",
    kind: "dweller",
    title: "西方宽耳蝠 / 彼氏鼠耳蝠",
    copies: 3,
    faces: [
      {
        id: "western-barbastelle",
        title: "西方宽耳蝠",
        side: "top",
        cost: 2,
        tags: ["蝙蝠", "哺乳", "夜行"],
        basePoints: 3,
        scoreRules: [{ type: "per-tag", tag: "夜行", points: 1, label: "夜间群落" }],
      },
      {
        id: "bechsteins-bat",
        title: "彼氏鼠耳蝠",
        side: "top",
        cost: 2,
        tags: ["蝙蝠", "哺乳", "夜行"],
        basePoints: 2,
        onPlay: [{ type: "draw-deck", count: 1, label: "穿林飞行" }],
        scoreRules: [{ type: "per-cave", points: 1, label: "洞穴族群" }],
      },
    ],
  },
  {
    id: "butterfly-duo",
    kind: "dweller",
    title: "榆蛱蝶 / 紫闵蛱蝶",
    copies: 4,
    faces: [
      {
        id: "white-admiral",
        title: "榆蛱蝶",
        side: "top",
        cost: 0,
        tags: ["蝴蝶", "昆虫"],
        basePoints: 0,
        scoreRules: [{ type: "per-tag", tag: "蝴蝶", points: 1, label: "蝶群" }],
      },
      {
        id: "purple-emperor",
        title: "紫闵蛱蝶",
        side: "top",
        cost: 1,
        tags: ["蝴蝶", "昆虫"],
        basePoints: 1,
        scoreRules: [{ type: "per-tag", tag: "昆虫", points: 1, label: "林冠昆虫" }],
      },
    ],
  },
  {
    id: "roe-deer-red-deer",
    kind: "dweller",
    title: "西方狍 / 赤鹿",
    copies: 4,
    faces: [
      {
        id: "roe-deer",
        title: "西方狍",
        side: "left",
        cost: 2,
        tags: ["鹿类", "偶蹄动物", "哺乳", "食草"],
        basePoints: 3,
        scoreRules: [{ type: "per-tree", points: 1, label: "林间穿行" }],
      },
      {
        id: "red-deer",
        title: "赤鹿",
        side: "right",
        cost: 3,
        tags: ["鹿类", "偶蹄动物", "哺乳", "食草"],
        basePoints: 5,
        scoreRules: [{ type: "per-tag", tag: "鹿类", points: 1, label: "鹿群" }],
      },
    ],
  },
  {
    id: "fern-parasol-mushroom",
    kind: "dweller",
    title: "欧洲蕨 / 高大环柄菇",
    copies: 4,
    faces: [
      {
        id: "european-fern",
        title: "欧洲蕨",
        side: "bottom",
        cost: 1,
        tags: ["植物"],
        basePoints: 1,
        onPlay: [{ type: "draw-deck", count: 1, label: "林下扩展" }],
        scoreRules: [{ type: "per-tag", tag: "植物", points: 1, label: "草本层" }],
      },
      {
        id: "parasol-mushroom",
        title: "高大环柄菇",
        side: "bottom",
        cost: 1,
        tags: ["蘑菇"],
        basePoints: 2,
        scoreRules: [{ type: "per-tag", tag: "植物", points: 1, label: "腐殖共生" }],
      },
    ],
  },
];
